Update to rc02
eclipse-digitaltwin/aas4j pull request #17
Opened 2022-08-05 14:45 UTC by changqin26

Hi Sebastian, 

I updated all RDF examples under the resource. Can you please check them? I am not sure about my changes in ConceptDescription and DataSpecification parts.

2022-08-08 14:21 UTC, sebbader commented on dataformat-rdf/src/test/resources/Complete_Example.ttl
> +         <https://admin-shell.io/aas/3/0/RC02/Property/valueType>  "integer" ;
I think this should be "xs:int" or "xs:integer"

2022-08-08 14:21 UTC, sebbader commented on dataformat-rdf/src/test/resources/Complete_Example.ttl
> +            <https://admin-shell.io/aas/3/0/RC02/File/valueType>  "xsd:string" ; #TODO not a File?
Probably "application/pdf" makes more sense. And, shouldn't it be File/contentType?

2022-08-08 14:21 UTC, sebbader commented on dataformat-rdf/src/test/resources/Complete_Example.ttl
> +            <https://admin-shell.io/aas/3/0/RC02/File/valueType>  "xsd:string" ;
same as above with File

2022-08-08 14:21 UTC, sebbader commented on dataformat-rdf/src/test/resources/Complete_Example.ttl
> +<https://admin-shell.io/DataSpecificationTemplates/DataSpecificationIEC61360> rdf:type aas:DataSpecification ;
DataSpecificationIEC61360 is of type owl:Class

2022-08-08 14:21 UTC, sebbader commented on dataformat-rdf/src/test/resources/Complete_Example.ttl
> +<https://admin-shell.io/DataSpecificationTemplates/DataSpecificationIEC61360> rdf:type aas:DataSpecification ;
Possibly: 
<http://customer.com/DataSpecificationTemplates/9123_6345_7091_8456> rdf:type aas:DataSpecification ;

2022-08-08 14:21 UTC, sebbader commented on dataformat-rdf/src/test/resources/Complete_Example.ttl
> +       <https://admin-shell.io/DataSpecificationTemplates/DataSpecificationIEC61360/3/0/RC02/DataSpecificationIEC61360/preferredName> "Max. rotation speed"@en, "max. Drehzahl"@de ;
preferredNames

2022-08-08 14:21 UTC, sebbader commented on dataformat-rdf/src/test/resources/Complete_Example.ttl
> +       <https://admin-shell.io/DataSpecificationTemplates/DataSpecificationIEC61360/3/0/RC02/DataSpecificationIEC61360/definition> "Höchste zulässige Drehzahl, mit welcher der Motor oder die Speisein
definitions

2022-08-09 07:29 UTC, changqin26 commented on dataformat-rdf/src/test/resources/Complete_Example.ttl
> +<https://admin-shell.io/DataSpecificationTemplates/DataSpecificationIEC61360> rdf:type aas:DataSpecification ;
we need a deeper look into "dataSpecifiction" examples. Let's do it together.

2022-09-08 14:51 UTC, sebbader requested changes
Apart of the namespace, everything looks good!

2022-09-08 14:51 UTC, sebbader commented on dataformat-rdf/src/test/resources/AAS_Reference_shortExample.ttl
> +@prefix aas: <http://www.admin-shell.io/aas/3/0/RC02/> .
The was namespace will change with V3.0.5RC02, needs to be updated from <http://www.admin-shell.io/aas/3/0/RC02/> to <https://admin-shell.io/aas/3/0/RC02/>
This applies to all examples, not only to this one.

2022-09-09 07:50 UTC, changqin26 commented
Please review again. @sebbader

2022-09-09 09:14 UTC, sebbader commented
> Please review again. @sebbader

Please check my PR here: https://github.com/changqin26/aas4j/pull/1. My SHACL validator says that the examples are good with these changes.

2022-09-09 09:25 UTC, changqin26 commented
After merging your PR, I think we are good to go. @sebbader

2022-09-09 09:49 UTC, merged